variables:
  DOCKER_DRIVER: overlay2

publish chart:
  stage: build
  image:
    name: alpine/helm:3.0.2
    entrypoint: ["/bin/sh", "-c"]
  before_script:
    - apk add git
    - helm plugin install https://github.com/chartmuseum/helm-push
    - helm repo add ufc https://${CHARTMUSEUM_USER}:${CHARTMUSEUM_PASSWORD}@charts.biz.com
  script:
    - helm push . ufc --force
