{{- $fullName := include "ufc-be.fullname" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "ufc-be.labels" . | nindent 4 }}
type: Opaque
stringData:
  jwt-secret: {{ .Values.jwt.secret  }}
  oss-access-key-id: {{ .Values.oss.accessKeyId }}
  oss-access-key-secret: {{ .Values.oss.accessKeySecret }}
  mail-password: {{ .Values.mail.password }}
  sms-access-key-id: {{ .Values.sms.accessKeyId }}
  sms-access-key-secret: {{ .Values.sms.accessKeySecret }}
  wechat-token: {{ .Values.wechat.token }}
  wechat-app-secret: {{ .Values.wechat.appSecret }}
  wechat-pc-secret: {{ .Values.wechatPC.appSecret }}
  gexin-app-key: {{ .Values.gexin.appKey }}
  gexin-app-secret: {{ .Values.gexin.appSecret }}
  gexin-master-secret: {{ .Values.gexin.masterSecret }}
  redis-password: {{ .Values.redis.password }}
  wechat-work-key-secret: {{ .Values.wechatwork.key }}

  {{- if .Values.dingTalk.enabled }}
  ding-talk-signature: {{ .Values.dingTalk.signature }}
  {{- end }}

  {{- if .Values.arms.enabled }}
  arms-license-key: {{ .Values.arms.licenseKey }}
  {{- end }}

  {{- if not .Values.rabbitmq.enabled }}
  rabbitmq-password: {{ .Values.externalRabbitMq.password }}
  {{- end }}

  {{- if and .Values.rabbitmq.enabled .Values.rabbitmq.mqtt.enabled }}
  mqtt-password: {{ .Values.rabbitmq.mqtt.password }}
  {{- else }}
  mqtt-password: {{ .Values.externalMqtt.password }}
  {{- end }}

  {{- if .Values.redis.enabled }}
  reids-password: {{ .Values.redis.password }}
  {{- end }}

  {{- if not .Values.mysql.enabled }}
  mysql-password: {{ .Values.externalMySql.password }}
  {{- end }}

  {{- if .Values.tsdb.enabled }}
  tsdb-host: {{ .Values.tsdb.host }}
  tsdb-port: "{{ .Values.tsdb.port }}"
  {{- end }}
